# Install node.js version 8.10.0
FROM node:8.10.0

# Expose the port 8080
EXPOSE 8080

# Copy main.js to the production directory
COPY main.js .

# Run the following command to create the node.js application
CMD node main.js
