# RESOURCE QUOTA
apiVersion: v1
kind: ResourceQuota
metadata:
  name: nodejs-quota
spec:
  hard:
    pods: "4" # Use a maximum of 4 pods.
---
# SERVICE
apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
  labels:
    app: nodejs
spec:
  ports:
    - port: 8080 # Run the service on port 8080.
      targetPort: 8080
  selector:
    app: nodejs
  type: NodePort # Use a fixed port. "LoadBalancer" does not seem to work.
---
# DEPLOYMENT
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment
  labels:
    app: nodejs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodejs # Container name.
        image: martinvanzijl/test:v3 # Image (application).
        resources:
          requests:
            cpu: "25m" # Use a minimum of 25 milli-CPUs.
            memory: "25Mi" # Use a minimum of 25 MB memory.
          limits:
            cpu: "40m" # Use a maximum of 40 milli-CPUs.
            memory: "50Mi" # Use a maximum of 50 MB memory.
        ports:
        - containerPort: 8080
          name: nodejs
---
# AUTO-SCALING POLICY
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: nodejs-deployment
  namespace: nodejs-namespace
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nodejs-deployment
  minReplicas: 2 # Scale down to a minimum of 2 pods.
  maxReplicas: 4 # Scale up to a maximum of 4 pods.
  targetCPUUtilizationPercentage: 50

