# Install node.js version 6.4.2?
FROM node:6.14.2

# Expose the port 8080
EXPOSE 8080

# Copy main.js to the production directory
COPY main.js .

# Run the following command to create the node.js application
CMD node main.js
