# RESOURCE QUOTA
apiVersion: v1
kind: ResourceQuota
metadata:
  name: nginx-quota
spec:
  hard:
    pods: "4" # Use a maximum of 4 pods.
---
# SERVICE
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  ports:
    - port: 80 # Run the service on port 80.
      targetPort: 80
  selector:
    app: nginx
  type: NodePort # Use a fixed port. "LoadBalancer" does not seem to work.
---
# DEPLOYMENT
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx # Container name.
        image: nginx:1.15.6	# Image (application).
        resources:
          requests:
            cpu: "25m" # Use a minimum of 25 milli-CPUs.
            memory: "25Mi" # Use a minimum of 25 MB memory.
          limits:
            cpu: "40m" # Use a maximum of 40 milli-CPUs.
            memory: "50Mi" # Use a maximum of 50 MB memory.
        ports:
        - containerPort: 80
          name: nginx
---
# AUTO-SCALING POLICY
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: nginx-deployment
  namespace: nginx-namespace
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx-deployment
  minReplicas: 2 # Scale down to a minimum of 2 pods.
  maxReplicas: 4 # Scale up to a maximum of 4 pods.
  targetCPUUtilizationPercentage: 50

