# RESOURCE QUOTA
apiVersion: v1
kind: ResourceQuota
metadata:
  name: nodejs-quota
spec:
  hard:
    pods: "{{max_pods}}" # Use a maximum of 4 pods.
---
# SERVICE
apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
  labels:
    app: nodejs
spec:
  ports:
    - port: 8080 # Run the service on port 8080.
      targetPort: 8080
  selector:
    app: nodejs
  type: NodePort # Use a fixed port. "LoadBalancer" does not seem to work.
---
# DEPLOYMENT
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment
  labels:
    app: nodejs
spec:
  replicas: {{starting_pods}}
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodejs # Container name.
        image: martinvanzijl/test:latest # Image (application).
        resources:
          requests:
            cpu: "25m" # Use a minimum of 25 milli-CPUs.
            memory: "25Mi" # Use a minimum of 25 MB memory.
          limits:
            cpu: "100m" # Use a maximum of 100 milli-CPUs.
            memory: "200Mi" # Use a maximum of 200 MB memory.
        ports:
        - containerPort: 8080
          name: nodejs
---
# AUTO-SCALING POLICY
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: nodejs-deployment
  namespace: nodejs-namespace
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nodejs-deployment
  minReplicas: {{min_pods}}
  maxReplicas: {{max_pods}}
  targetCPUUtilizationPercentage: {{scale_cpu_threshold}}

